# Generated by Django 4.1.6 on 2023-02-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tag1',
        ),
    ]
