# Generated by Django 4.1.5 on 2023-01-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='articles'),
            preserve_default=False,
        ),
    ]
