# Generated by Django 4.1.5 on 2023-01-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nima',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
