# Generated by Django 4.1.7 on 2023-03-07 03:24

import apps.course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_difficulty_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(null=True, upload_to=apps.course.models.file_path_cover),
        ),
    ]
