# Generated by Django 4.1.7 on 2023-03-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_soldcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
