# Generated by Django 4.1.7 on 2023-03-11 07:16

import apps.course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_discount_price_course_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail_cover',
            field=models.ImageField(null=True, upload_to=apps.course.models.file_path_cover),
        ),
    ]
