# Generated by Django 4.1.6 on 2023-02-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
