# Generated by Django 4.1.6 on 2023-02-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_comment_podcast_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
