# Generated by Django 4.1.6 on 2023-02-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_podcast_description_comment_podcast_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='likes',
        ),
    ]
