# Generated by Django 4.1.6 on 2023-02-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_alter_comment_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='cat_image/'),
            preserve_default=False,
        ),
    ]
