# Generated by Django 4.1.6 on 2023-02-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0012_season_podcast_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='title',
            field=models.CharField(default=1, max_length=221),
            preserve_default=False,
        ),
    ]
