# Generated by Django 4.1.6 on 2023-02-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0014_alter_podcast_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.category'),
        ),
    ]
