# Generated by Django 4.1.6 on 2023-02-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0017_remove_like_user_like_author_alter_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='music',
        ),
    ]
