# Generated by Django 4.1.4 on 2022-12-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
