# Generated by Django 4.1.5 on 2023-02-02 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogs.article')),
            ],
        ),
        migrations.CreateModel(
            name='SubContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('is_wide', models.BooleanField()),
                ('sub_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.subcontent')),
            ],
        ),
    ]
