# Generated by Django 4.1.5 on 2023-02-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_subcontent_subcontentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontent',
            name='description2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
