# Generated by Django 4.1.5 on 2023-02-02 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_subcontent_description2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcontentimage',
            old_name='image',
            new_name='image2',
        ),
        migrations.AlterField(
            model_name='subcontent',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description2', to='blogs.article'),
        ),
        migrations.AlterField(
            model_name='subcontentimage',
            name='sub_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image2', to='blogs.subcontent'),
        ),
    ]
