# Generated by Django 4.1.5 on 2023-02-03 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_image_subcontentimage_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontent',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subcontent', to='blogs.article'),
        ),
        migrations.AlterField(
            model_name='subcontentimage',
            name='sub_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontentimage', to='blogs.subcontent'),
        ),
    ]
